"""v0.4 article info in saved article

Revision ID: 8d2b6ee75132
Revises: 5662f1255cad
Create Date: 2023-04-18 11:54:26.469797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2b6ee75132'
down_revision = '5662f1255cad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_article', sa.Column('article_info', sa.JSON(), nullable=True))
    op.drop_constraint('saved_article_article_id_fkey', 'saved_article', type_='foreignkey')
    op.drop_column('saved_article', 'article_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_article', sa.Column('article_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key('saved_article_article_id_fkey', 'saved_article', 'article', ['article_id'], ['id'])
    op.drop_column('saved_article', 'article_info')
    # ### end Alembic commands ###
